use sysy_il::c_ast::{
  Block, CompUnit, FuncDef, FuncType, Stmt, Exp, PrimaryExp, Number, UnaryExp, 
  UnaryOp, MulExp, MulOp, AddExp, AddOp , RelExp, RelOp, EqExp, EqOp, LAndExp, LOrExp
};

grammar;

match {
  // Skip space and comments
  r"\s*" => {},
  r"//[^\n\r]*[\n\r]*" => {},
  r"/\*([^*]|\*+[^*/])*\*+/" => {},
  // And just use the basic one
  _
}

// Define ComputUnit, with string as return value
// parser would return FuncDef
pub CompUnit: CompUnit = <func_def: FuncDef> => CompUnit { <> };

FuncDef: FuncDef = {
  <func_type: FuncType> <ident: Ident> "(" ")" <block: Block> => {
    FuncDef { <> }
  }
};

FuncType: FuncType = "int" => FuncType::Int;

Block: Block = "{" <stmt: Stmt> "}" => Block { <> };

Stmt: Stmt = "return" <exp: Exp> ";" => Stmt { <> };

Exp: Exp = <lor_exp: LOrExp> => Exp { lor_exp: Box::new(lor_exp) };

PrimaryExp: PrimaryExp = {
  "(" <exp: Exp> ")" => PrimaryExp::Exp { exp: Box::new(exp) },
  <num: Number> => PrimaryExp::Number { <> },
};

Number: Number = <num: IntConst> => <>;

UnaryExp: UnaryExp = {
  <primary_exp: PrimaryExp> => UnaryExp::Primary{ primary_exp: Box::new(primary_exp) },
  <op: UnaryOp> <e: UnaryExp> => UnaryExp::OpUnary{ unary_op: op, unary_exp: Box::new(e) }
};

// If you match identifer, return the string
// <> represents the result matched by the regex
Ident: String = r"[_a-zA-Z][_a-zA-Z0-9]*" => <>.to_string();

// Capture the number
IntConst: i32 = {
  r"[1-9][0-9]*" => i32::from_str_radix(<>, 10).unwrap(),
  r"0[0-7]*" => i32::from_str_radix(<>, 8).unwrap(),
  r"0[xX][0-9a-fA-F]+" => i32::from_str_radix(&<>[2..], 16).unwrap(),
}

UnaryOp: UnaryOp = {
  "+" => UnaryOp::PLUS,
  "-" => UnaryOp::MINUS,
  "!" => UnaryOp::BANG,
  "~" => UnaryOp::TILDE,
}

MulExp: MulExp = {
  <u_exp: UnaryExp> => MulExp::Unary{ unary_exp: Box::new(u_exp) },
  <m_exp: MulExp> <op: MulOp> <u_exp: UnaryExp> => MulExp::MulOpUnary{ 
    mul_exp: Box::new(m_exp),
    op: op,
    unary_exp: Box::new(u_exp) 
  },
}

AddExp: AddExp = {
  <m_exp: MulExp> => AddExp::Mul{ mul_exp: Box::new(m_exp) },
  <a_exp: AddExp> <op: AddOp> <m_exp: MulExp> => AddExp::AddOpMul{ 
    add_exp: Box::new(a_exp),
    op: op,
    mul_exp: Box::new(m_exp) 
  },
}

AddOp: AddOp = {
  "+" => AddOp::PLUS,
  "-" => AddOp::MINUS,
}

MulOp: MulOp = {
  "*" => MulOp::STAR,
  "/" => MulOp::SLASH,
  "%" => MulOp::PERCENT,
}

RelExp: RelExp = {
  <a_exp: AddExp> => RelExp::Add { add_exp: Box::new(a_exp) },
  <r_exp: RelExp> <op: RelOp> <a_exp: AddExp> => RelExp::RelOpAdd { 
    rel_exp: Box::new(r_exp),
    op: op,
    add_exp: Box::new(a_exp),
  }
}

RelOp: RelOp = {
  "<" => RelOp::LT,
  "<=" => RelOp::LE,
  ">" => RelOp::GT,
  ">=" => RelOp::GE,
}

EqExp: EqExp = {
  <r_exp: RelExp> => EqExp::Rel { rel_exp: Box::new(r_exp) },
  <e_exp: EqExp> <op: EqOp> <r_exp: RelExp> => EqExp::EqOpRel {
    eq_exp: Box::new(e_exp),
    op: op,
    rel_exp: Box::new(r_exp),
  }
}

EqOp: EqOp = {
  "==" => EqOp::EQ,
  "!=" => EqOp::NE,
}

LAndExp: LAndExp = {
  <e_exp: EqExp> => LAndExp::Eq { eq_exp: Box::new(e_exp) },
  <land_exp: LAndExp> "&&" <e_exp: EqExp> => LAndExp::LAndEq {
    land_exp: Box::new(land_exp),
    eq_exp: Box::new(e_exp),
  }
}

LOrExp: LOrExp = {
  <l_exp: LAndExp> => LOrExp::LAnd { land_exp: Box::new(l_exp) },
  <lor_exp: LOrExp> "||" <land_exp: LAndExp> => LOrExp::LOrLAnd {
    lor_exp: Box::new(lor_exp),
    land_exp: Box::new(land_exp),
  }
}
